apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamgate

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - api-gateway.yaml
  - transcoder.yaml
  - upload.yaml
  - streaming.yaml
  - metadata.yaml
  - cache.yaml
  - auth.yaml
  - worker.yaml
  - prometheus.yaml
  - grafana.yaml

commonLabels:
  app.kubernetes.io/name: streamgate
  app.kubernetes.io/instance: streamgate
  app.kubernetes.io/managed-by: kubectl
